# Generated by Django 6.0.3 on 2026-03-20 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of billing month')),
                ('invoice_number', models.CharField(blank=True, default=None, max_length=30, null=True, unique=True)),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('elec_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_amt', models.DecimalField(decimal_places=2, default=0, help_text='Sum of BillLineItem amounts (auto-updated by refresh_total)', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_day', models.IntegerField(choices=[(1, '1st'), (5, '5th'), (10, '10th'), (25, '25th')], default=1)),
                ('grace_days', models.PositiveIntegerField(default=5)),
                ('elec_rate', models.DecimalField(decimal_places=2, default=7.0, max_digits=6)),
                ('water_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=6)),
                ('tmr_api_key', models.CharField(blank=True, max_length=255)),
                ('tmr_secret', models.CharField(blank=True, max_length=255)),
                ('dunning_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraChargeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tmr_ref', models.CharField(max_length=255, unique=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('webhook_payload', models.JSONField(default=dict)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
