# Generated by Django 6.0.3 on 2026-03-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='dormitory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='core.dormitory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='billing.bill'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('room', 'month')},
        ),
    ]
