# Generated by Django 6.0.3 on 2026-03-30 14:37

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='notification_channel',
            field=models.CharField(choices=[('line_only', 'LINE Only'), ('sms_only', 'SMS Only'), ('both', 'LINE + SMS')], default='line_only', max_length=20),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='sms_sender_name',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='payment',
            name='webhook_payload',
            field=models.JSONField(default=dict, encoder=apps.core.models.UUIDEncoder),
        ),
    ]
