# Generated by Django 6.0.3 on 2026-03-30 04:39

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='new_value',
            field=models.JSONField(blank=True, encoder=apps.core.models.UUIDEncoder, help_text='Snapshot of changed fields after save', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='old_value',
            field=models.JSONField(blank=True, encoder=apps.core.models.UUIDEncoder, help_text='Snapshot of changed fields before save', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='record_id',
            field=models.CharField(blank=True, help_text='PK of the affected record (UUID or int as string)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='detail',
            field=models.JSONField(blank=True, default=dict, encoder=apps.core.models.UUIDEncoder),
        ),
    ]
