# Generated by Django 6.0.3 on 2026-03-15 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dormitory_invoice_prefix_userdormitoryrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dormitory',
            field=models.ForeignKey(blank=True, help_text='Active/current dormitory context for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.dormitory'),
        ),
    ]
