# Generated by Django 6.0.3 on 2026-03-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audit_log_old_new_fields'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_buildings',
            field=models.ManyToManyField(blank=True, help_text='Buildings assigned to this user (building_manager role only)', related_name='managers', to='rooms.building'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('owner', 'Owner'), ('building_manager', 'Building Manager'), ('staff', 'Staff'), ('tenant', 'Tenant')], default='tenant', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdormitoryrole',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('owner', 'Owner'), ('building_manager', 'Building Manager'), ('staff', 'Staff'), ('tenant', 'Tenant')], default='staff', max_length=20),
        ),
    ]
