# Generated by Django 6.0.3 on 2026-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_building_manager_role_and_managed_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='line_user_id',
            field=models.CharField(blank=True, help_text='LINE User ID for push notifications (owner/staff)', max_length=100),
        ),
    ]
