# Generated by Django 6.0.3 on 2026-03-20 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dormitory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='rooms.building')),
                ('dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dormitory')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('base_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dormitory')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.floor')),
            ],
            options={
                'unique_together': {('floor', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('water_prev', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_curr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_photo', models.ImageField(blank=True, null=True, upload_to='meters/water/')),
                ('elec_prev', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elec_curr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elec_photo', models.ImageField(blank=True, null=True, upload_to='meters/elec/')),
                ('reading_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dormitory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dormitory')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='rooms.room')),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
    ]
