# Generated by Django 6.0.3 on 2026-03-10 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('core', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(choices=[('all', 'All Tenants'), ('building', 'By Building'), ('floor', 'By Floor')], default='all', max_length=20)),
                ('audience_ref', models.CharField(blank=True, help_text='Building name or Floor number if targeted', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='broadcasts/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='core.dormitory')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='parcels/')),
                ('carrier', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DunningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('pre_7d', '7 Days Before Due'), ('pre_3d', '3 Days Before Due'), ('pre_1d', '1 Day Before Due'), ('due', 'Due Date'), ('post_1d', '1 Day Overdue'), ('post_7d', '7 Days Overdue'), ('post_15d', '15 Days Overdue')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_logs', to='billing.bill')),
            ],
            options={
                'ordering': ['sent_at'],
                'unique_together': {('bill', 'trigger_type')},
            },
        ),
    ]
